### ISSUE TITLE
Any chance of adding Kaspersky Network Agent?

### ISSUE THREAD

**Issue by FranPregernik** [secure-diversITy/arch_kesl#1]
Described here https://support.kaspersky.com/KSC/11/en-US/3305.htm

Is there a way to get the debs for that and include them in the PCKGBUILD?

Best regards,
Fran

P.S. Thank you for this package.

**Comment by se-di** [comment]
as far as I understand the network agent must be downloaded from the kaspersky web console or administration server and I am not sure how custom that is then. so likely no that won't come.

**Comment by FranPregernik** [comment]
I understand. Thank you for the feedback.
